### ISSUE TITLE
Cache not only by id?

### ISSUE THREAD

**Issue by vladgolubev** [ricepo/mongo-stash#1]
Firstly, thanks for the module!

What about caching not only by id? Couldn't you stringify mongo query selector and treat it same as id?

**Comment by jluchiji** [comment]
Hi, thanks for your kind words!

Unfortunately, this module was designed specifically for the use case where most of the time only individual records are being manipulated. Caching query results by `JSON.stringify(query)` as the key has a problem where we would never know when underlying data has changed. An immediate problem would be the following:

```js

const result1 = stash.find(somequery);

stash.insert(something); // Assuming something matches some query

const result2 = stash.find(somequery);

```

...in which case, `result2` would not include `something`, which is unacceptable in our particular use case. A short cache TTL may partially solve this issue, but we did not want to make that tradeoff.

Therefore, sadly, we do not plan to introduce query caching at this point. If you have an idea as to how to overcome the above issue without sacrificing data integrity or performance, I would be more than happy to work with you to implement query caching (which is also a feature we really need).

**Comment by vladgolubev** [comment]
Agree, a legitimate tradeoff.
However there are some modules that can help:
* https://github.com/crcn/sift.js (find)
* https://github.com/alykoshin/micromongo (find, remove, insert)
* https://github.com/kawanet/obop (find, update)

Looks like with the help of these modules we can update all the cached objects affected by mongo query. (at least `$set`, `$unset`, `$rename`, `$inc`, `$pull` and `$push`)

What do you think?

**Comment by jluchiji** [comment]
Thanks for the tips!

I looked into this really carefully. The only way I can think of is to loop through every cache entry, checking if it matches the update criteria and updating it. Considering that this would need to happen on every insert/update/delete operation, things can get fairly ugly. Plus, we would need to make sure that all changes are consistently applied to all cached entries.

I personally think that this consistency-performance tradeoff is not worth it. Query-based caching will require significant engineering effort, and may end up degrading performance rather than speeding things up. Properly administered MongoDB is a very fast database, and at the amount of data where query-based caching makes sense, the above approach would slow things down to a crawl.

**Comment by jluchiji** [comment]
One possible way to do it is to transparently pass all queries through an in-memory implementation of MongoDB, like sergeyksv/tingodb or mWater/minimongo. That, however, would introduce a lot of bulk to this module, which I would really like to keep as thin as possible.

**Comment by vladgolubev** [comment]
@jluchiji absolutely agree with you, it rather looks like solving a nonexistent problem. As for me a proper answer is here:

> Properly administered MongoDB is a very fast database, and at the amount of data where query-based caching makes sense, the above approach would slow things down to a crawl.

So I suggest adding above-mentioned to README and closing the issue.

Thanks for the investigation!
